# Parámetros de conexión a la base de datos MapaMundi en SGDB MySQL
jdbc.driver = com.mysql.cj.jdbc.Driver
jdbc.url = jdbc:mysql://23.21.171.246:3306/mapa_mundi
jdbc.usuario = isidoronm
jdbc.password = 1234

